version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Allow security-only updates to be auto-merged by Dependabot if configured in repo settings
    # We will pin transitive packages manually if a security advisory requires it.
    # Optionally, add labels for filtering.
    labels:
      - "dependencies"
      - "dependabot"
