name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore DSM-NeuralPlay.sln

    - name: Build
      run: dotnet build DSM-NeuralPlay.sln --no-restore --configuration Release

    - name: SchemaExport (SQLite fallback)
      run: dotnet run --project InitializeDb/InitializeDb.csproj -- --mode=schemaexport

    - name: Run tests
      run: dotnet test DSM-NeuralPlay.sln --no-build --verbosity normal
